### ISSUE TITLE
modus-themes-headings and font weight

### ISSUE THREAD

**Issue by uliw** [protesilaos/modus-themes#101]
if I execute the following code
```
(setq modus-themes-headings
       '((1 . (variable-pitch regular 1.0))
 	 (2 . (variable-pitch regular 1.0))
	 (3 . (variable-pitch regular 1.0))
 	 ))

(load-theme 'modus-operandi)
```
It will adjust the font height as expected, but the font weight remains bold. Did I miss something, or is this a bug?

**Comment by protesilaos** [comment]
> From: Ulrich Wortmann ***@***.***>
> Date: Wed, 13 Mar 2024 12:21:56 -0700
>
> if I execute the following code
> ```
> (setq modus-themes-headings
>        '((1 . (variable-pitch regular 1.0))
>  	 (2 . (variable-pitch regular 1.0))
> 	 (3 . (variable-pitch regular 1.0))
>  	 ))
>
> (load-theme 'modus-operandi)
> ```
> It will adjust the font height as expected, but the font weight remains bold. Did I miss something, or is this a bug?

Strange... Your code is fine and it works as expected on my end. Could
it be that your 'variable-pitch' font is thicker and so it seems to be
bold?

Place the cursor over a letter in the heading and do 'M-x describe-char'.
It will produce a Help buffer that will tell you what font family is
used there.
       
-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by uliw** [comment]
describe-face results in the following:
```
Face: org-level-2 (sample) (customize this face)

Documentation:
Face used for level 2 headlines.

Defined in ‘org-faces.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: 1.0
           Weight: bold
            Slant: unspecified
       Foreground: #123555
DistantForeground: unspecified
       Background: #E5F4FB
        Underline: unspecified
         Overline: #123555
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: modus-themes-heading-2

[back]
```

If I change the font in the following way,
```
(set-face-attribute 'org-level-2 nil :height '1.3517 :box nil :weight 'normal :background "white" :foreground "black") 
```
it works as expected. So the font works just fine.  BTW, this is with emas 29.2 using the builtin modus themes on linux
