### ISSUE TITLE
Alacritty, SSH, and Emacs terminal mode not using correct background

### ISSUE THREAD

**Issue by KarlJoad** [protesilaos/modus-themes#136]
My systems:
```
localhost$ cat /etc/os-release
NAME="Guix System"
ID=guix
PRETTY_NAME="Guix System"
LOGO=guix-icon
HOME_URL="https://guix.gnu.org"
DOCUMENTATION_URL="https://guix.gnu.org/en/manual"
SUPPORT_URL="https://guix.gnu.org/en/help"
BUG_REPORT_URL="https://lists.gnu.org/mailman/listinfo/bug-guix"

localhost$ guix system describe
Generation 36	Mar 22 2025 20:38:50	(current)
  file name: /var/guix/profiles/system-36-link
  canonical file name: /gnu/store/k3ywviia1gg4102lbmghbgsf8b6vsqjs-system
  label: GNU with Linux-Ipmi 6.13.7
  bootloader: grub-efi-removable-bootloader
  root device: UUID: 0c469309-3ce2-4780-bf8c-279f7f02e155
  kernel: /gnu/store/pyzws7hhnwg4jdrvhxp5jl7wg1w2nyvf-linux-ipmi-6.13.7/bzImage
  channels:
    nonguix:
      repository URL: https://gitlab.com/nonguix/nonguix
      branch: master
      commit: a96e2451bda5aaf9b48339edee392c6a3017d730
    synnax:
      repository URL: https://github.com/KarlJoad/synnax.git
      branch: master
      commit: 75e2ebce0bcc2c92044e0364cfe5ccc7d013fd28
    guix:
      repository URL: https://git.savannah.gnu.org/git/guix.git
      branch: master
      commit: 5bf7d80535720077aec104a9904480d08b9b4f2b
  configuration file: /gnu/store/5biagaamzaxw7wwchfzmqw73dql597rk-configuration.scm

localhost$ guix home describe
Generation 76	Mar 22 2025 20:57:25	(current)
  file name: /var/guix/profiles/per-user/karljoad/guix-home-76-link
  canonical file name: /gnu/store/dwayk160bm23jgvxsabk6iz4y0gn3n4d-home
  channels:
    nonguix:
      repository URL: https://gitlab.com/nonguix/nonguix
      branch: master
      commit: a96e2451bda5aaf9b48339edee392c6a3017d730
    synnax:
      repository URL: https://github.com/KarlJoad/synnax.git
      branch: master
      commit: 75e2ebce0bcc2c92044e0364cfe5ccc7d013fd28
    guix:
      repository URL: https://git.savannah.gnu.org/git/guix.git
      branch: master
      commit: 5bf7d80535720077aec104a9904480d08b9b4f2b
  configuration file: /gnu/store/3wnppsl1zpsjgpb9l7rqllwg6c1gq01k-configuration.scm

remotehost$ emacs
... Inside Emacs
M-x emacs-version <RET>
Emacs version: GNU Emacs 30.1 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.2, Xaw3d scroll bars)

remotehost:~/.emacs.d/elpaca/repos/modus-themes$ git log
commit f3cd4d6983566dab0ef3bcddf812cfd565d00d08 (HEAD -> main, origin/main, origin/HEAD)
Merge: 63ab46d ab56e28
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Thu Feb 20 08:47:29 2025 +0200
...
```

The general flow in this problem is:

```sh
<open alacritty>
localhost$ echo $TERM
alacritty

localhost$ echo $COLORTERM
COLORTERM=truecolor

localhost$ ssh <remote-host-with-emacs>
remotehost$ echo $TERM
xterm-256color

remotehost$ echo $COLORTERM
COLORTERM=truecolor

remotehost$ emacs
...
```
My default theme is modus-vivendi, so I expect a black background. My Emacs config is [in my repository](https://github.com/KarlJoad/Emacs_dotfiles).
However, Emacs has a gray background at this point instead of a black one. (See image below)
![Image](https://github.com/user-attachments/assets/9c097581-9df5-4468-8f63-caa796705b9c)

If `COLORTERM` is not set, then I end up with gray normal text on the gray background. Setting `COLORTERM=truecolor` gives me the correct contrast; I get white normal text on the gray background (as seen in the image).

If I use urxvt or xterm, I get the black background and everything works.

This problem is **not** related to windowing system (X11 or Wayland). I get the same behavior on both. I use StumpWM on my desktop and KDE Plasma 6 (Wayland) on my laptop, and they both have this gray background. The image above shows that I am inside tmux (`$TERM=tmux-256color`), but this problem occurs **outside** of tmux as well, so tmux is not the issue.

I also have a configuration for alacritty:
```toml
# Generated by Guix Home. DO NOT EDIT!
[font]
size = 9

# Colors (Modus Vivendi) from https://github.com/anhsirk0/alacritty-themes
[colors.bright]
black = "#535353"
red = "#ef8b50"
green = "#70b900"
yellow = "#c0c530"
blue = "#79a8ff"
magenta = "#fe00f6"
cyan = "#4ae2f0"
white = "#989898"

[colors.cursor]
cursor = "#f4f4f4"
text = "#323232"

[colors.normal]
black = "#323232"
red = "#ff8059"
green = "#44bc44"
yellow = "#d0bc00"
blue = "#2fafff"
magenta = "#f78fe7"
cyan = "#00d3d0"
white = "#ffffff"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#3c3c3c"
text = "#ffffff"
```

I just want to make sure this is a problem on my end with `$TERM` changing across machines vs. something in modus.
