### ISSUE TITLE
Indentation of description lists

### ISSUE THREAD

**Issue by TitusMu** [protesilaos/modus-themes#87]
Dear Prot,

I often use description lists in orgmode. And I like your modus themes, as they make everything easier to read. In the description lists though, the theme I used before is doing it better. The spaces before and the space after the character that is used to display the item (I use org-superstar) are done in a variable-pitch-font in the modus themes, as opposed to a fixed-pitch-font in doom-solarized-light, where I come from. That results in the text being very close to the symbol at the start of the line in your themes, making it harder to read. And, what is worse, it is responsible for an unorderly indent. With fixed-pitch, all the list-sub-items that are further indented start where the text of the upper level started. With variable-pitch, they start much earlier and it looks "fuzzy". See the picture I added. 

It seems, doom-solarized-light uses the face org-list-dt for the spaces around the item symbol, which is fixed-pitch. In the modus themes, no special face is used for the spaces. Is there a way for me to make the modus themes use a fixed-pitch font there, to make things look nicer?

First example is modus operandi tinted, second example is doom-solarized-light.

![Indent](https://github.com/protesilaos/modus-themes/assets/110761073/ff7768af-567f-4e69-99f7-d9fad9151116)

I use emacs 29.1, org 9.6.6 and modus themes 4.2.0.

Thank you so much for your great themes! And for any help with this wish of mine.

Titus

**Comment by protesilaos** [comment]
Hello @TitusMu!  Looking at the screenshots, it seems that doom-solarized-light makes the dashes in the list monospaced.  Can you check what is the underlying face by placing the cursor over the dash and doing `M-x describe-char`?  A Help buffer will pop up and it will mention the applicable face, if any, towards the bottom.

Alternatively, send me the text and I can give it a try.

**Comment by TitusMu** [comment]
The space characters before the dash show (org-indent), written like this in brackets. The dash itself shows (org-list-dt), also in brackets. Thank you for looking into this!

**Comment by protesilaos** [comment]
Can you do `M-x describe-face` for `org-list-dt` with the doom-solarized-light theme?  It will produce a help buffer.  We need to learn what attributes it has.  Please share the contents of that Help buffer.

**Comment by TitusMu** [comment]
This is the output on `org-list-dt`:

```
Face: org-list-dt (sample) (customize this face)

Documentation:
Default face for definition terms in lists.

Defined in ‘org-faces.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #268bd2
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```


And `org-indent` has the following output on `M-x describe-face`:

```
Face: org-indent (sample) (customize this face)

Documentation:
Face for outline indentation.
The default is to make it look like whitespace.  But you may find it
useful to make it ever so slightly different.

Defined in ‘org-indent.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: org-hide
```

The inherited face `org-hide` ist defined as:

```
Face: org-hide (sample) (customize this face)

Documentation:
Face used to hide leading stars in headlines.
The foreground color of this face should be equal to the background
color of the frame.

Defined in ‘org-faces.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #FDF6E3
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```
