### ISSUE TITLE
Zooming in with .org files while using the modus themes breaks org elements.

### ISSUE THREAD

**Issue by PurpleAzurite** [protesilaos/modus-themes#9]
Currently, zooming in the view when using either modus themes results in broken display of tables and other org elements. This issue is unique to the modus themes, and not other emacs themes.

![2021-09-23_09-39](https://user-images.githubusercontent.com/48709923/134464209-56d06d81-1206-4b6b-9d27-b2ab758853a3.png)

**Comment by protesilaos** [comment]
Thank you @PurpleAzurite for reporting this!

Which version of the themes are you using?  Is it from MELPA or the one built in to Emacs28?  Just for me to know where to check.

**Comment by PurpleAzurite** [comment]
No thank you for making the themes. They are lovely.

Theme version: Build: HEAD -> main, origin/main, origin/HEAD bbdd033 2021-09-18 11:19:37 +0300
Emacs version: 27.2
Org version: 9.5

**Comment by PurpleAzurite** [comment]
Setting (setq modus-themes-no-mixed-fonts t) fixes the issue.

**Comment by protesilaos** [comment]
The issue has to be with Emacs27.  I am building it now.

**Comment by protesilaos** [comment]
I have been trying to reproduce this on Emacs 27, but I still get the expected results.  Which leads me to believe that something else is messing things up on your end.  Can you place the point/cursor over the smaller text and do `M-x describe-char` (`=C-u C-x =` by default)?  It will produce a help buffer, which might give us some hints.

**Comment by PurpleAzurite** [comment]
```
             position: 3 of 13 (15%), column: 2
            character: T (displayed as T) (codepoint 84, #o124, #x54)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x54
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Left-to-right (strong), a:ASCII, l:Latin, r:Roman
             to input: type "C-x 8 RET 54" or "C-x 8 RET LATIN CAPITAL LETTER T"
          buffer code: #x54
            file code: #x54 (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    ftcrhb:-JB-JetBrains Mono-normal-normal-normal-*-18-*-*-*-m-0-iso10646-1 (#x89)

Character code properties: customize what to show
  name: LATIN CAPITAL LETTER T
  general-category: Lu (Letter, Uppercase)
  decomposition: (84) ('T')

There is an overlay here:
 From 1 to 14
  face                 hl-line
  priority             -50
  window               nil


There are text properties here:
  face                 org-document-info-keyword
  font-lock-fontified  t
  fontified            t
  line-prefix          ""
  wrap-prefix          ""
  ws-butler-chg        chg

```

**Comment by protesilaos** [comment]
Thanks! What about if you follow the link on this line?

```
  face                 org-document-info-keyword
```

**Comment by protesilaos** [comment]
Also, what is the output of `M-x describe-symbol` (`C-h o`) for `fixed-pitch`?

**Comment by PurpleAzurite** [comment]
Face:

```
Documentation:
Default face for highlighting the current line in Hl-Line mode.

Defined in ‘hl-line.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: t
          Inherit: modus-themes-hl-line

This face was introduced, or its default value was changed, in
version 22.1 of Emacs.

[back]
```

**Comment by PurpleAzurite** [comment]
Fixed pitch:

```
Face: fixed-pitch (sample) (customize this face)

Documentation:
The basic fixed-pitch face.

Defined in ‘faces.el’.


           Family: JetBrains Mono
          Foundry: JB
            Width: unspecified
           Height: 135
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: #<font-spec nil JB JetBrains Mono nil iso10646-1 nil nil nil 18 nil 100 nil nil>
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified

```
